apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  #nameResolution:
  #  component: "consul"
    #configuration:
    #  selfRegister: true
  tracing:
    samplingRate: "1"
    zipkin:      
      endpointAddress: "http://zipkin:9411/api/v2/spans" 
      #endpointAddress: "http://jaeger:9412/api/v2/spans"
  metrics:
    enabled: true